// Output_v1/Gemini1_0/JS/extracted_code/translation/ReactToAngular_high_avg/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs';
import {
  addTodo,
  clearCompleted,
  destroy,
  edit,
  save,
  toggle,
  toggleAll,
} from './store/actions/todo.actions';
import { Todo } from './store/models/todo.model';
import { selectTodos } from './store/selectors/todo.selectors';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  todos$: Observable<Todo[]>;
  activeTodoCount: number;
  completedCount: number;
  nowShowing: string;
  ALL_TODOS = 'all';
  ACTIVE_TODOS = 'active';
  COMPLETED_TODOS = 'completed';

  constructor(private store: Store) {
    this.todos$ = this.store.select(selectTodos);
  }

  ngOnInit(): void {
    this.todos$.subscribe((todos) => {
      this.activeTodoCount = todos.filter((todo) => !todo.completed).length;
      this.completedCount = todos.filter((todo) => todo.completed).length;
    });
  }

  handleNewTodoKeyDown(event: KeyboardEvent): void {
    if (event.keyCode !== 13) {
      return;
    }

    event.preventDefault();

    const val = (document.getElementById('newField') as HTMLInputElement).value.trim();

    if (val) {
      this.store.dispatch(addTodo({ title: val }));
      (document.getElementById('newField') as HTMLInputElement).value = '';
    }
  }

  toggleAll(event: Event): void {
    const target = event.target as HTMLInputElement;
    const checked = target.checked;
    this.store.dispatch(toggleAll({ checked }));
  }

  toggle(todo: Todo): void {
    this.store.dispatch(toggle({ todo }));
  }

  destroy(todo: Todo): void {
    this.store.dispatch(destroy({ todo }));
  }

  edit(todo: Todo): void {
    this.store.dispatch(edit({ todo }));
  }

  save(todo: Todo, text: string): void {
    this.store.dispatch(save({ todo, text }));
  }

  cancel(): void {
    this.store.dispatch(edit({ todo: null }));
  }

  clearCompleted(): void {
    this.store.dispatch(clearCompleted());
  }
}
<div class="todoapp">
  <header class="header">
    <h1>todos</h1>
    <input
      #newField
      class="new-todo"
      placeholder="What needs to be done?"
      (keydown)="handleNewTodoKeyDown($event)"
      autoFocus
    />
  </header>
  <section class="main" *ngIf="todos.length > 0">
    <input
      id="toggle-all"
      class="toggle-all"
      type="checkbox"
      [checked]="activeTodoCount === 0"
      (change)="toggleAll($event)"
    />
    <label for="toggle-all">Mark all as complete</label>
    <ul class="todo-list">
      <li
        *ngFor="let todo of shownTodos"
        [class.completed]="todo.completed"
        [class.editing]="editing === todo.id"
      >
        <div class="view">
          <input
            class="toggle"
            type="checkbox"
            [checked]="todo.completed"
            (change)="toggle(todo)"
          />
          <label (dblclick)="edit(todo)">{{ todo.title }}</label>
          <button class="destroy" (click)="destroy(todo)"></button>
        </div>
        <input
          *ngIf="editing === todo.id"
          class="edit"
          [value]="todo.title"
          (blur)="save(todo, $event.target.value)"
          (keydown)="handleKeyDown($event, todo)"
          (change)="handleChange($event)"
        />
      </li>
    </ul>
  </section>
  <footer class="footer" *ngIf="todos.length > 0">
    <span class="todo-count">
      <strong>{{ activeTodoCount }}</strong> {{ activeTodoCount | pluralize }} left
    </span>
    <ul class="filters">
      <li>
        <a [routerLink]="['/']" [class.selected]="nowShowing === ALL_TODOS"
          >All</a
        >
      </li>
      <li>
        <a
          [routerLink]="['/active']"
          [class.selected]="nowShowing === ACTIVE_TODOS"
          >Active</a
        >
      </li>
      <li>
        <a
          [routerLink]="['/completed']"
          [class.selected]="nowShowing === COMPLETED_TODOS"
          >Completed</a
        >
      </li>
    </ul>
    <button class="clear-completed" *ngIf="completedCount > 0" (click)="clearCompleted()">
      Clear completed
    </button>
  </footer>
</div>

// Output/GPT41mini_0414/JS/contextual_experiment/update_react/1744818168/src/app.tsx
import React, { useState, useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { RootState } from './store/todoSlice';
import { addTodo, toggleAll, toggle, destroy, save, clearCompleted } from './store/todoSlice';
import { TodoItem } from './components/TodoItem';
import { TodoFooter } from './components/TodoFooter';
import { ALL_TODOS, ACTIVE_TODOS, COMPLETED_TODOS } from './constants';

const ENTER_KEY = 13;

const App: React.FC = () => {
  const todos = useSelector((state: RootState) => state.todos.todos);
  const dispatch = useDispatch();

  const [nowShowing, setNowShowing] = useState<string>(ALL_TODOS);
  const [editing, setEditing] = useState<string | null>(null);
  const [newTodo, setNewTodo] = useState<string>('');

  useEffect(() => {
    function onHashChange() {
      switch (window.location.hash) {
        case '#/active':
          setNowShowing(ACTIVE_TODOS);
          break;
        case '#/completed':
          setNowShowing(COMPLETED_TODOS);
          break;
        default:
          setNowShowing(ALL_TODOS);
          break;
      }
    }

    window.addEventListener('hashchange', onHashChange);
    onHashChange();

    return () => window.removeEventListener('hashchange', onHashChange);
  }, []);

  const handleNewTodoKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.keyCode !== ENTER_KEY) {
      return;
    }
    event.preventDefault();
    const val = newTodo.trim();
    if (val) {
      dispatch(addTodo(val));
      setNewTodo('');
    }
  };

  const handleToggleAll = (event: React.ChangeEvent<HTMLInputElement>) => {
    dispatch(toggleAll(event.target.checked));
  };

  const handleToggle = (id: string) => {
    dispatch(toggle(id));
  };

  const handleDestroy = (id: string) => {
    dispatch(destroy(id));
  };

  const handleEdit = (id: string) => {
    setEditing(id);
  };

  const handleSave = (id: string, text: string) => {
    dispatch(save({ id, title: text }));
    setEditing(null);
  };

  const handleCancel = () => {
    setEditing(null);
  };

  const handleClearCompleted = () => {
    dispatch(clearCompleted());
  };

  const shownTodos = todos.filter(todo => {
    switch (nowShowing) {
      case ACTIVE_TODOS:
        return !todo.completed;
      case COMPLETED_TODOS:
        return todo.completed;
      default:
        return true;
    }
  });

  const activeTodoCount = todos.reduce((accum, todo) => (todo.completed ? accum : accum + 1), 0);
  const completedCount = todos.length - activeTodoCount;

  return (
    <div>
      <header className="header">
        <h1>todos</h1>
        <input
          className="new-todo"
          placeholder="What needs to be done?"
          value={newTodo}
          onChange={e => setNewTodo(e.target.value)}
          onKeyDown={handleNewTodoKeyDown}
          autoFocus
        />
      </header>
      {todos.length > 0 && (
        <section className="main">
          <input
            id="toggle-all"
            className="toggle-all"
            type="checkbox"
            onChange={handleToggleAll}
            checked={activeTodoCount === 0}
          />
          <label htmlFor="toggle-all">Mark all as complete</label>
          <ul className="todo-list">
            {shownTodos.map(todo => (
              <TodoItem
                key={todo.id}
                todo={todo}
                onToggle={() => handleToggle(todo.id)}
                onDestroy={() => handleDestroy(todo.id)}
                onEdit={() => handleEdit(todo.id)}
                editing={editing === todo.id}
                onSave={text => handleSave(todo.id, text)}
                onCancel={handleCancel}
              />
            ))}
          </ul>
        </section>
      )}
      {(activeTodoCount > 0 || completedCount > 0) && (
        <TodoFooter
          count={activeTodoCount}
          completedCount={completedCount}
          nowShowing={nowShowing}
          onClearCompleted={handleClearCompleted}
        />
      )}
    </div>
  );
};

export default App;
