// Output/AmazonNovaPremier/JS/contextual_experiment/update_react/1747397582/components/TodoItem.tsx
import React, { useState, useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { toggleTodo, removeTodo, updateTodo } from '../features/todos/todoSlice';

interface TodoItemProps {
  todo: Todo;
}

const TodoItem: React.FC<TodoItemProps> = ({ todo }) => {
  const [editText, setEditText] = useState(todo.title);
  const [editing, setEditing] = useState(false);
  const dispatch = useDispatch();

  const handleSubmit = () => {
    if (editText.trim()) {
      dispatch(updateTodo({ id: todo.id, title: editText }));
    } else {
      dispatch(removeTodo(todo.id));
    }
    setEditing(false);
  };

  const handleEdit = () => {
    setEditing(true);
    setEditText(todo.title);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') {
      setEditText(todo.title);
      setEditing(false);
    } else if (e.key === 'Enter') {
      handleSubmit();
    }
  };

  useEffect(() => {
    if (editing) {
      const node = document.querySelector(`[data-id="${todo.id}"]`);
      node?.focus();
      node?.setSelectionRange(editText.length, editText.length);
    }
  }, [editing, editText]);

  return (
    <li className={`${todo.completed ? 'completed' : ''} ${editing ? 'editing' : ''}`}>
      <div className="view">
        <input
          className="toggle"
          type="checkbox"
          checked={todo.completed}
          onChange={() => dispatch(toggleTodo(todo.id))}
        />
        <label onDoubleClick={handleEdit}>{todo.title}</label>
        <button className="destroy" onClick={() => dispatch(removeTodo(todo.id))} />
      </div>
      <input
        data-id={todo.id}
        className="edit"
        value={editText}
        onBlur={handleSubmit}
        onChange={(e) => setEditText(e.target.value)}
        onKeyDown={handleKeyDown}
      />
    </li>
  );
};

export default TodoItem;

// Output_v1/GPT4_Turbo/JS/extracted_code/translation/ReactToAngular_high_avg/todo-item/todo-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Todo } from '../todo.model';
import { Store } from '@ngrx/store';
import { toggleTodo, destroyTodo, editTodo } from '../store/todos.actions';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css']
})
export class TodoItemComponent {
  @Input() todo: Todo;
  editing: boolean = false;
  editText: string = '';

  constructor(private store: Store) {}

  toggleTodo() {
    this.store.dispatch(toggleTodo({ id: this.todo.id }));
  }

  destroyTodo() {
    this.store.dispatch(destroyTodo({ id: this.todo.id }));
  }

  editTodo() {
    this.editing = true;
    this.editText = this.todo.title;
  }

  saveTodo() {
    if (this.editText.trim().length) {
      this.store.dispatch(editTodo({ id: this.todo.id, title: this.editText.trim() }));
      this.editing = false;
    }
  }

  cancelEdit() {
    this.editing = false;
  }
}
<li [class.completed]="todo.completed" [class.editing]="editing">
  <div class="view">
    <input class="toggle" type="checkbox" (change)="toggleTodo()" [checked]="todo.completed">
    <label (dblclick)="editTodo()">{{todo.title}}</label>
    <button class="destroy" (click)="destroyTodo()"></button>
  </div>
  <input class="edit" [(ngModel)]="editText" (blur)="saveTodo()" *ngIf="editing">
</li>
