// Output/GPT4o_0806_0813/JS/contextual_experiment/update_react/1723553924/src/components/App.tsx
import React, { useState, useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { RootState } from '../store/store';
import { addTodo, toggleTodo, deleteTodo, editTodo, clearCompleted, toggleAll } from '../store/todoSlice';
import { TodoFooter } from './Footer';
import { TodoItem } from './TodoItem';
import { ALL_TODOS, ACTIVE_TODOS, COMPLETED_TODOS, ENTER_KEY } from '../constants/constants';

const App: React.FC = () => {
  const [nowShowing, setNowShowing] = useState(ALL_TODOS);
  const [editing, setEditing] = useState<string | null>(null);
  const todos = useSelector((state: RootState) => state.todos.todos);
  const dispatch = useDispatch();

  useEffect(() => {
    const handleHashChange = () => {
      const nowShowing = window.location.hash.replace(/^#\//, '');
      setNowShowing(nowShowing || ALL_TODOS);
    };
    window.addEventListener('hashchange', handleHashChange);
    handleHashChange();
    return () => window.removeEventListener('hashchange', handleHashChange);
  }, []);

  const handleNewTodoKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.keyCode !== ENTER_KEY) {
      return;
    }

    event.preventDefault();

    const input = event.currentTarget;
    const val = input.value.trim();

    if (val) {
      dispatch(addTodo(val));
      input.value = '';
    }
  };

  const shownTodos = todos.filter(todo => {
    switch (nowShowing) {
      case ACTIVE_TODOS:
        return !todo.completed;
      case COMPLETED_TODOS:
        return todo.completed;
      default:
        return true;
    }
  });

  const todoItems = shownTodos.map(todo => (
    <TodoItem
      key={todo.id}
      todo={todo}
      onToggle={() => dispatch(toggleTodo(todo.id))}
      onDestroy={() => dispatch(deleteTodo(todo.id))}
      onEdit={() => setEditing(todo.id)}
      editing={editing === todo.id}
      onSave={(text) => {
        dispatch(editTodo({ id: todo.id, title: text }));
        setEditing(null);
      }}
      onCancel={() => setEditing(null)}
    />
  ));

  const activeTodoCount = todos.reduce((accum, todo) => todo.completed ? accum : accum + 1, 0);
  const completedCount = todos.length - activeTodoCount;

  return (
    <div>
      <header className="header">
        <h1>todos</h1>
        <input
          className="new-todo"
          placeholder="What needs to be done?"
          onKeyDown={handleNewTodoKeyDown}
          autoFocus={true}
        />
      </header>
      {todos.length > 0 && (
        <section className="main">
          <input
            id="toggle-all"
            className="toggle-all"
            type="checkbox"
            onChange={(e) => dispatch(toggleAll(e.currentTarget.checked))}
            checked={activeTodoCount === 0}
          />
          <label htmlFor="toggle-all">
            Mark all as complete
          </label>
          <ul className="todo-list">
            {todoItems}
          </ul>
        </section>
      )}
      {(activeTodoCount || completedCount) && (
        <TodoFooter
          count={activeTodoCount}
          completedCount={completedCount}
          nowShowing={nowShowing}
          onClearCompleted={() => dispatch(clearCompleted())}
        />
      )}
    </div>
  );
};

export default App;

// Output_v1/Gemini1_0/JS/extracted_code/translation/ReactToAngular_high_avg/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { Observable } from 'rxjs';
import {
  addTodo,
  clearCompleted,
  destroy,
  edit,
  save,
  toggle,
  toggleAll,
} from './store/actions/todo.actions';
import { Todo } from './store/models/todo.model';
import { selectTodos } from './store/selectors/todo.selectors';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  todos$: Observable<Todo[]>;
  activeTodoCount: number;
  completedCount: number;
  nowShowing: string;
  ALL_TODOS = 'all';
  ACTIVE_TODOS = 'active';
  COMPLETED_TODOS = 'completed';

  constructor(private store: Store) {
    this.todos$ = this.store.select(selectTodos);
  }

  ngOnInit(): void {
    this.todos$.subscribe((todos) => {
      this.activeTodoCount = todos.filter((todo) => !todo.completed).length;
      this.completedCount = todos.filter((todo) => todo.completed).length;
    });
  }

  handleNewTodoKeyDown(event: KeyboardEvent): void {
    if (event.keyCode !== 13) {
      return;
    }

    event.preventDefault();

    const val = (document.getElementById('newField') as HTMLInputElement).value.trim();

    if (val) {
      this.store.dispatch(addTodo({ title: val }));
      (document.getElementById('newField') as HTMLInputElement).value = '';
    }
  }

  toggleAll(event: Event): void {
    const target = event.target as HTMLInputElement;
    const checked = target.checked;
    this.store.dispatch(toggleAll({ checked }));
  }

  toggle(todo: Todo): void {
    this.store.dispatch(toggle({ todo }));
  }

  destroy(todo: Todo): void {
    this.store.dispatch(destroy({ todo }));
  }

  edit(todo: Todo): void {
    this.store.dispatch(edit({ todo }));
  }

  save(todo: Todo, text: string): void {
    this.store.dispatch(save({ todo, text }));
  }

  cancel(): void {
    this.store.dispatch(edit({ todo: null }));
  }

  clearCompleted(): void {
    this.store.dispatch(clearCompleted());
  }
}
<div class="todoapp">
  <header class="header">
    <h1>todos</h1>
    <input
      #newField
      class="new-todo"
      placeholder="What needs to be done?"
      (keydown)="handleNewTodoKeyDown($event)"
      autoFocus
    />
  </header>
  <section class="main" *ngIf="todos.length > 0">
    <input
      id="toggle-all"
      class="toggle-all"
      type="checkbox"
      [checked]="activeTodoCount === 0"
      (change)="toggleAll($event)"
    />
    <label for="toggle-all">Mark all as complete</label>
    <ul class="todo-list">
      <li
        *ngFor="let todo of shownTodos"
        [class.completed]="todo.completed"
        [class.editing]="editing === todo.id"
      >
        <div class="view">
          <input
            class="toggle"
            type="checkbox"
            [checked]="todo.completed"
            (change)="toggle(todo)"
          />
          <label (dblclick)="edit(todo)">{{ todo.title }}</label>
          <button class="destroy" (click)="destroy(todo)"></button>
        </div>
        <input
          *ngIf="editing === todo.id"
          class="edit"
          [value]="todo.title"
          (blur)="save(todo, $event.target.value)"
          (keydown)="handleKeyDown($event, todo)"
          (change)="handleChange($event)"
        />
      </li>
    </ul>
  </section>
  <footer class="footer" *ngIf="todos.length > 0">
    <span class="todo-count">
      <strong>{{ activeTodoCount }}</strong> {{ activeTodoCount | pluralize }} left
    </span>
    <ul class="filters">
      <li>
        <a [routerLink]="['/']" [class.selected]="nowShowing === ALL_TODOS"
          >All</a
        >
      </li>
      <li>
        <a
          [routerLink]="['/active']"
          [class.selected]="nowShowing === ACTIVE_TODOS"
          >Active</a
        >
      </li>
      <li>
        <a
          [routerLink]="['/completed']"
          [class.selected]="nowShowing === COMPLETED_TODOS"
          >Completed</a
        >
      </li>
    </ul>
    <button class="clear-completed" *ngIf="completedCount > 0" (click)="clearCompleted()">
      Clear completed
    </button>
  </footer>
</div>
