// Output_v1/GPT4_Turbo/JS/extracted_code/translation/AngularToReact_avg_avg_2/src/App.tsx
import React, { useState } from 'react';
import { useAppDispatch, useAppSelector } from './app/hooks';
import { addTodo, clearCompleted, toggleAll } from './features/todos/todosSlice';
import TodoList from './components/TodoList';

function App() {
  const [input, setInput] = useState('');
  const dispatch = useAppDispatch();
  const todos = useAppSelector(state => state.todos.todos);

  const handleAddTodo = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;
    dispatch(addTodo(input.trim()));
    setInput('');
  };

  const handleToggleAll = (e: React.ChangeEvent<HTMLInputElement>) => {
    dispatch(toggleAll(e.target.checked));
  };

  const handleClearCompleted = () => {
    dispatch(clearCompleted());
  };

  return (
    <div className="todoapp">
      <header className="header">
        <h1>todos</h1>
        <form onSubmit={handleAddTodo}>
          <input
            className="new-todo"
            placeholder="What needs to be done?"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            autoFocus
          />
        </form>
      </header>
      <section className="main">
        {todos.length > 0 && (
          <>
            <input
              id="toggle-all"
              className="toggle-all"
              type="checkbox"
              onChange={handleToggleAll}
            />
            <label htmlFor="toggle-all">Mark all as complete</label>
            <TodoList />
          </>
        )}
      </section>
      <footer className="footer">
        <span className="todo-count">
          <strong>{todos.filter(todo => !todo.completed).length}</strong> items left
        </span>
        <button className="clear-completed" onClick={handleClearCompleted}>
          Clear completed
        </button>
      </footer>
    </div>
  );
}

export default App;

// Output/GPT4_Turbo/JS/extracted_code/translation/ReactToAngular_high_avg/app.component.ts
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { addTodo, clearCompleted, toggleAll } from './store/todos.actions';
import { Todo } from './todo.model';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  newTodoTitle: string = '';
  nowShowing: string = 'all';

  constructor(private store: Store<{ todos: Todo[] }>) {}

  addTodo() {
    if (this.newTodoTitle.trim().length) {
      this.store.dispatch(addTodo({ title: this.newTodoTitle.trim() }));
      this.newTodoTitle = '';
    }
  }

  toggleAllTodos(event: any) {
    this.store.dispatch(toggleAll({ completed: event.target.checked }));
  }

  clearCompletedTodos() {
    this.store.dispatch(clearCompleted());
  }

  updateNowShowing(showing: string) {
    this.nowShowing = showing;
  }
}
<header class="header">
  <h1>todos</h1>
  <input class="new-todo" placeholder="What needs to be done?" [(ngModel)]="newTodoTitle" (keyup.enter)="addTodo()" autofocus>
</header>
<section class="main">
  <input id="toggle-all" class="toggle-all" type="checkbox" (change)="toggleAllTodos($event)">
  <label for="toggle-all">Mark all as complete</label>
  <ul class="todo-list">
    <app-todo-item *ngFor="let todo of (todos | async)" [todo]="todo"></app-todo-item>
  </ul>
</section>
<app-todo-footer [nowShowing]="nowShowing" (clearCompleted)="clearCompletedTodos()" (updateNowShowing)="updateNowShowing($event)"></app-todo-footer>
